
package br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INFSEConsultas", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM.serialization.ObjectFactory.class,
    br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM.ObjectFactory.class
})
public interface INFSEConsultas {


    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarSituacaoLoteRps", action = "http://tempuri.org/INFSEConsultas/ConsultarSituacaoLoteRps")
    @WebResult(name = "ConsultarSituacaoLoteRpsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarSituacaoLoteRps", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarSituacaoLoteRps")
    @ResponseWrapper(localName = "ConsultarSituacaoLoteRpsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarSituacaoLoteRpsResponse")
    public String consultarSituacaoLoteRps(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://tempuri.org/INFSEConsultas/ConsultarNfsePorRps")
    @WebResult(name = "ConsultarNfsePorRpsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarNfsePorRps", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarNfsePorRps")
    @ResponseWrapper(localName = "ConsultarNfsePorRpsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarNfsePorRpsResponse")
    public String consultarNfsePorRps(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://tempuri.org/INFSEConsultas/ConsultarLoteRps")
    @WebResult(name = "ConsultarLoteRpsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarLoteRps", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarLoteRps")
    @ResponseWrapper(localName = "ConsultarLoteRpsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarLoteRpsResponse")
    public String consultarLoteRps(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfse", action = "http://tempuri.org/INFSEConsultas/ConsultarNfse")
    @WebResult(name = "ConsultarNfseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarNfse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarNfse")
    @ResponseWrapper(localName = "ConsultarNfseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarNfseResponse")
    public String consultarNfse(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

}
