
package br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INFSEGeracao", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM.serialization.ObjectFactory.class,
    br.com.moveti.erpmove.fiscal.nfe.webservices.NFSE.CONTAGEM.ObjectFactory.class
})
public interface INFSEGeracao {


    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://tempuri.org/INFSEGeracao/RecepcionarLoteRps")
    @WebResult(name = "RecepcionarLoteRpsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RecepcionarLoteRps", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RecepcionarLoteRps")
    @ResponseWrapper(localName = "RecepcionarLoteRpsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RecepcionarLoteRpsResponse")
    public String recepcionarLoteRps(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

    /**
     * 
     * @param xmlEnvio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarNfse", action = "http://tempuri.org/INFSEGeracao/CancelarNfse")
    @WebResult(name = "CancelarNfseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelarNfse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarNfse")
    @ResponseWrapper(localName = "CancelarNfseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarNfseResponse")
    public String cancelarNfse(
        @WebParam(name = "xmlEnvio", targetNamespace = "http://tempuri.org/")
        String xmlEnvio);

}
